language: c

compiler: gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libtalloc-dev gdb strace realpath
 - sudo pip install cpp-coveralls

script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make -C src loader.exe loader-m32.exe build.h && env CFLAGS=--coverage LDFLAGS='--coverage' make -C src proot && env PATH=/bin:/usr/bin:/sbin:/usr/sbin:$PWD/src make -C tests; fi

after_success:
  - coveralls --build-root src --exclude tests --gcov-options '\-lp'

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   # via the "travis encrypt" command using the project repo's public key
   - secure: "kZW0uXwtUnMsD9Qdd1tiBWoTBL5Jo73b8FPARbtBuwaOUWvt76zQhAQcdSFp3uQsN/e24ZJ/gMZ8eIUoQ0s1zDdB5tOGiv3twVhRRMrNrE8HnoAg4PgimMp7NBIL79vXYcenabajp/nP0w5Ynw6YSxI3hhvkQSSkEwDavo+S769frCnw6WBd6KapypUJAp1pv3ZhJiwT8EHXjoDyWANFUJy4iPzBpe7nvKj/hTkiTvp/Y9yvdAROrxIDMj9br6+Z27fuiyO5d2thWAXwGPFlOAB7Pr0UTV7efp0dVvSzgGPLRdUJVtXvLC4P9E+z8c41SnQdsu+2Pj1Q//tMjpN82vqgcrygx/8wqVPXya2slH9uupmbaxuon/kWjGcE81r78EO/gqzCF5rP/7IJ+N3bo42wnC/Of3VoZR7obpEXcTADfbsXuUVkau4uSarERbOZIFZLCsoJ5so7jpCmbSAsfCmxV01RfZbZ10C9f2KQrW22Kt3OhPNRYeQcHAmZ6xAJAh3YfyutTs1sgZGFmuJzPNb5BmwBjZAswM/XNB8zCHHidX1FqfLwtE72DMxr3fqOuY/kuLlK80s1bx57wtziqI1ApeY6Jt4dCXEt6B+T92p2ZpKnMAwDhFaQgg+iNB3RRxa+yqBxTw3JFWiDXqQyOmEEfoWSjfeKpeUdZ6hmkm0="

addons:
  coverity_scan:
    project:
      name: "termux/proot"
      description: "proot"
    notification_email: fredrik@fornwall.net
    build_command_prepend:
    build_command: make -C src
    branch_pattern: coverity_scan
