TERMUX_PKG_HOMEPAGE=https://dev.lovelyhq.com/libburnia
TERMUX_PKG_DESCRIPTION="Library for reading, mastering and writing optical discs"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="Leonid Pliushch <leonid.pliushch@gmail.com>"
TERMUX_PKG_VERSION=1.5.2
TERMUX_PKG_REVISION=2
TERMUX_PKG_SRCURL=http://files.libburnia-project.org/releases/libburn-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=7b32db1719d7f6516cce82a9d00dfddfb3581725db732ea87d41ea8ef0ce5227
TERMUX_PKG_BREAKS="libburn-dev"
TERMUX_PKG_REPLACES="libburn-dev"
