os:
  - linux
  - osx
language: node_js

sudo: required

node_js:
  - "4.4.0"
  - "6.2.1"
  - "8.11.3"
  - "10.4.0"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - libpcap-dev

cache:
  directories:
    - node_modules
