# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

strategy:
  matrix:
    Linux_py37:
      vmImage: 'ubuntu-16.04'
      python.version: '3.7'
    Linux_py38:
      vmImage: 'ubuntu-16.04'
      python.version: '3.8'
    macOS_py37:
      vmImage: 'macOS-10.15'
      python.version: '3.7'
    macOS_py38:
      vmImage: 'macOS-latest'
      python.version: '3.8'
    Windows_py37:
      vmImage: 'vs2017-win2016'
      python.version: '3.7'
    Windows_py38:
      vmImage: 'windows-latest'
      python.version: '3.8'
    Windows_pyPre:
      vmImage: 'vs2017-win2016'
      python.version: 'Pre'
  maxParallel: 4

pool:
  vmImage: '$(vmImage)'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    architecture: 'x64'
  displayName: 'Use Python $(python.version)'
  condition: and(succeeded(), ne(variables['python.version'], 'Pre'))

- task: stevedower.python.InstallPython.InstallPython@1
  displayName: 'Use prerelease Python'
  inputs:
    prerelease: true
  condition: and(succeeded(), eq(variables['python.version'], 'Pre'))

- bash: |
    set -e
    case "$(python -c 'import sys; print(sys.platform)')" in
    linux)
      sudo apt update
      sudo apt install \
        cm-super \
        dvipng \
        ffmpeg \
        gdb \
        gir1.2-gtk-3.0 \
        graphviz \
        inkscape \
        libcairo2 \
        libgirepository-1.0.1 \
        lmodern \
        fonts-freefont-otf \
        poppler-utils \
        texlive-pictures \
        texlive-fonts-recommended \
        texlive-latex-base \
        texlive-latex-extra \
        texlive-latex-recommended \
        texlive-xetex texlive-luatex
      ;;
    darwin)
      brew cask install xquartz
      brew install pkg-config ffmpeg imagemagick mplayer ccache
      ;;
    win32)
      ;;
    *)
      exit 1
      ;;
    esac
  displayName: 'Install dependencies'

- bash: |
    python -m pip install --upgrade pip
    python -m pip install -r requirements/testing/travis_all.txt -r requirements/testing/travis_extra.txt ||
      [[ "$PYTHON_VERSION" = 'Pre' ]]
  displayName: 'Install dependencies with pip'

- bash: |
    python -m pip install -ve . ||
      [[ "$PYTHON_VERSION" = 'Pre' ]]
  displayName: "Install self"

- script: env
  displayName: 'print env'

- bash: |
    PYTHONFAULTHANDLER=1 python -m pytest --junitxml=junit/test-results.xml -raR --maxfail=50 --timeout=300 --durations=25 --cov-report= --cov=lib -n 2 ||
      [[ "$PYTHON_VERSION" = 'Pre' ]]
  displayName: 'pytest'

- bash: |
    bash <(curl -s https://codecov.io/bash)  -f "!*.gcov" -X gcov
  displayName: 'Upload to codecov.io'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-results.xml'
    testRunTitle: 'Python $(python.version)'
  condition: succeededOrFailed()

- publish: $(System.DefaultWorkingDirectory)/result_images
  artifact: $(Agent.JobName)-result_images
  condition: and(failed(), ne(variables['python.version'], 'Pre'))
