language: python

matrix:
  include:
    - os: linux
      python: 3.6

    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6.1

install:
  - "./.travis/install.sh"


script:
  - "./.travis/run.sh"
